---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlenaGithub/configserver.git
          #only include username and password when it is private repo
security:
  user:
    name: alena
    password: alena123         